# packages needed for EAO development and testing
name: eao_env

channels:
  - conda-forge
  - defaults

dependencies:
  - python==3.13.7
  - pip
  - jupyter
  - pytest <= 8.4.2
  - pytest-cov <= 7.0.0
  - numpy <= 2.3.3
  - pandas <= 2.3.3
  - scipy <= 1.16.1
  - openpyxl <= 3.1.5
  - cvxpy <= 1.7.2
  - cvxopt <= 1.3.2
  - pyscipopt <= 5.6.0
  - networkx <= 3.5
  - matplotlib <= 3.10.6    
  - pip:
    - waterfall_ax==1.0.0 # needed for a graph in a sample notebook - can be removed if not needed
