name: Run all notebooks [manual]

on:
  workflow_dispatch:
      
jobs:
  run-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Conda
        uses: conda-incubator/setup-miniconda@v3
        with:
          auto-update-conda: true
          miniconda-version: "latest"
          python-version: "3.13.7"
          activate-environment: eao_env
          environment-file: environment.yml
          channels: conda-forge
          conda-remove-defaults: "true"   

      - name: Run the notebooks...
        id: run_notebooks
        continue-on-error: true
        run: |
          conda init bash
          source ~/.bashrc
          conda activate eao_env
          python -m ipykernel install --user --name=eao_env
          pip install eaopack
          python doc/source/samples/run_notebook_samples.py

      - name: Check if all notebooks run with no issues...
        run: |
            if [ "${{ steps.run_notebooks.outcome }}" == "success" ]; then
              echo '{"status": "passed"}' > notebooks_status.json
            else
              echo '{"status": "failed"}' > notebooks_status.json
            fi

      - name: Badge creation (notebooks)
        run: python .github/badges/generate_notebook_badge.py


      - name: Commit Notebook Badge in gh-pages
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config --global user.name "actions-user"
          git config --global user.email "actions@github.com"          
          git clone https://x-access-token:${GITHUB_TOKEN}@github.com/RIVACON/EAO.git --branch gh-pages --single-branch gh-pages
          rm -f gh-pages/badges/notebook-badge.svg
          mv .github/badges/notebook-badge.svg gh-pages/badges/notebook-badge.svg
          cd gh-pages
          touch .nojekyll
          echo $(date) > last_build.txt
          git pull
          git add .
          git commit -m "Update Notebook Badge" -a || true
          git push

      - name: Produce a red mark if the notebook tests failed
        run: |
            if [ "${{ steps.run_notebooks.outcome }}" != "success" ]; then
              echo "Notebook successfully executed"
              exit 0
            else
              echo "At least one notebook failed."
              exit 1
            fi
