name: TestsBadgesDocs [push main, manual]

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  run-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Conda
        uses: conda-incubator/setup-miniconda@v3
        with:
          auto-update-conda: true
          miniconda-version: "latest"
          python-version: "3.13.7"
          activate-environment: eao_env
          environment-file: environment.yml
          channels: conda-forge
          conda-remove-defaults: "true"          

      - name: Run tests and coverage...
        id: run_tests_and_coverage
        continue-on-error: true
        run: |
          conda init bash
          source ~/.bashrc
          conda activate eao_env
          pytest --cov=. --cov-report=json:coverage.json

      - name: Check if all tests are successful...
        run: |
            if [ "${{ steps.run_tests_and_coverage.outcome }}" == "success" ]; then
              echo '{"status": "passed"}' > test_status.json
            else
              echo '{"status": "failed"}' > test_status.json
            fi

      - name: Badge Creation (test, coverage)
        run: python .github/badges/generate_cov_and_test_badges.py


      - name: Run the notebooks...
        id: run_notebooks
        continue-on-error: true
        run: |
          conda init bash
          source ~/.bashrc
          conda activate eao_env
          python -m ipykernel install --user --name=eao_env
          pip install eaopack
          python doc/source/samples/run_notebook_samples.py

      - name: Check if all notebooks run with no issues...
        run: |
            if [ "${{ steps.run_notebooks.outcome }}" == "success" ]; then
              echo '{"status": "passed"}' > notebooks_status.json
            else
              echo '{"status": "failed"}' > notebooks_status.json
            fi

      - name: Badge creation (notebooks)
        run: python .github/badges/generate_notebook_badge.py


      - name: Build the docs
        run: |
          conda init bash
          source ~/.bashrc
          conda activate eao_env
          conda install pandoc
          pip install sphinx nbsphinx sphinx_rtd_theme
          sphinx-build -b html doc/source/ doc/build


      - name: Commit Notebook Badge in gh-pages
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config --global user.name "actions-user"
          git config --global user.email "actions@github.com"          
          git clone https://x-access-token:${GITHUB_TOKEN}@github.com/RIVACON/EAO.git --branch gh-pages --single-branch gh-pages
          rm -f gh-pages/badges/coverage-badge.svg
          rm -f gh-pages/badges/tests-badge.svg
          rm -f gh-pages/badges/notebook-badge.svg
          mv .github/badges/notebook-badge.svg gh-pages/badges/notebook-badge.svg
          mv .github/badges/coverage-badge.svg gh-pages/badges/coverage-badge.svg
          mv .github/badges/tests-badge.svg gh-pages/badges/tests-badge.svg
          mv notebooks_status.json gh-pages/badges/notebooks_status.json
          mv test_status.json gh-pages/badges/test_status.json
          cp -r doc/build/* gh-pages/
          cd gh-pages
          touch .nojekyll
          echo $(date) > last_build.txt
          git pull
          git add .
          git commit -m "Updating Badges and Documentation" -a || true
          git push
          if grep -q "failed" badges/test_status.json; then
            echo "At least one unittest failed."
            exit 1 
          else
            echo "All tests were successfull."
          fi
          if grep -q "failed" badges/notebooks_status.json; then
            echo "At least one notebook failed."
            exit 1 
          else
            echo "All notebooks were successfull."
          fi
