name: Unittests_Notebooks_NoBadges [push dev, manual]

on:
  push:
    branches:
      - develop
  workflow_dispatch:

jobs:
  run-tests:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash -l {0} # Automatically activates conda for every step

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Conda
        uses: conda-incubator/setup-miniconda@v3
        with:
          auto-update-conda: true
          miniconda-version: "latest"
          python-version: "3.13.7"
          activate-environment: eao_env
          environment-file: environment.yml
          channels: conda-forge
          conda-remove-defaults: "true"          

      - name: Run tests and coverage...
        id: run_tests_and_coverage
        run: |
          conda init bash
          source ~/.bashrc
          conda activate eao_env
          pytest --cov=. --cov-report=json:coverage.json

      - name: Run the notebooks...
        id: run_notebooks
        run: |
          # Inject the root folder into Python's search path
          export PYTHONPATH=$PYTHONPATH:$GITHUB_WORKSPACE        
          # conda init bash
          # source ~/.bashrc
          #conda activate eao_env
          #export PYTHONPATH=$PYTHONPATH:$(pwd)/../..
          #export PYTHONPATH=$PYTHONPATH:$(pwd)/../../..
          #export PYTHONPATH=$PYTHONPATH:$(pwd)/../../../..
          python -m ipykernel install --user --name=eao_env
          python doc/source/samples/run_notebook_samples.py
